onst json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type","Access-Control-Allow-Methods":"POST,OPTIONS",...extra}});
const enc=new TextEncoder();
function b64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function unb64(s){const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function hashPassword(password,salt){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:120000,hash:"SHA-256"},key,256);return b64(new Uint8Array(bits))}
async function makeHash(password){const salt=crypto.randomUUID();return salt+":"+await hashPassword(password,salt)}
async function checkHash(password,stored){const [salt,hash]=String(stored||"").split(":");return !!salt&&!!hash&&(await hashPassword(password,salt))===hash}
async function sign(payload,secret){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(payload));return b64(new Uint8Array(sig))}
async function adminCookie(username,secret){const payload=b64(enc.encode(JSON.stringify({u:username,r:"admin",exp:Date.now()+86400000})));return payload+"."+await sign(payload,secret)}
async function isAdmin(request,env){const c=request.headers.get("Cookie")||"";const m=c.match(/idleb_admin=([^;]+)/);if(!m||!env.AUTH_SECRET)return false;const [payload,sig]=m[1].split(".");if(!payload||!sig||(await sign(payload,env.AUTH_SECRET))!==sig)return false;try{const p=JSON.parse(new TextDecoder().decode(unb64(payload)));return p.r==="admin"&&p.exp>Date.now()&&p.u===(env.ADMIN_USERNAME||"admin")}catch{return false}}
async function sendEmail(env,to,username,code){if(!env.EMAILJS_SERVICE_ID||!env.EMAILJS_TEMPLATE_ID||!env.EMAILJS_PUBLIC_KEY)return false;const params={to_email:to,email:to,user_email:to,username,verification_code:code,code};const r=await fetch("https://api.emailjs.com/api/v1.0/email/send",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({service_id:env.EMAILJS_SERVICE_ID,template_id:env.EMAILJS_TEMPLATE_ID,user_id:env.EMAILJS_PUBLIC_KEY,template_params:params})});return r.ok}
export async function onRequest({request,env}){if(request.method==="OPTIONS")return new Response("",{status:204,headers:{"Access-Control-Allow-Origin":"*"}});if(request.method!=="POST")return json({error:"Method not allowed"},405);if(!env.DB)return json({error:"D1 binding DB is missing"},500);let b;try{b=await request.json()}catch{return json({error:"Invalid JSON"},400)};const action=b.action,username=String(b.username||"").trim(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");
if(action==="login"){const adminUser=env.ADMIN_USERNAME||"admin",adminPass=env.ADMIN_PASSWORD||"Idleb@2025";if(username===adminUser){if(password!==adminPass)return json({error:"بيانات الإدارة غير صحيحة"},401);const cookie=await adminCookie(adminUser,env.AUTH_SECRET||"change-this-secret");return json({ok:true,role:"admin",user:{username:adminUser,email:env.ADMIN_EMAIL||"",isAdmin:true} ,},200,{"Set-Cookie":`idleb_admin=${cookie}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=86400`})}
if(!username||!email||!password)return json({error:"أكمل بيانات الدخول"},400);const row=await env.DB.prepare("SELECT username,email,password_hash,is_verified,balance,created_at FROM users WHERE username=?1 OR email=?2 LIMIT 1").bind(username,email).first();if(!row)return json({error:"ACCOUNT_NOT_FOUND"},404);if(!(await checkHash(password,row.password_hash)))return json({error:"كلمة المرور غير صحيحة"},401);if(!row.is_verified)return json({error:"الحساب غير مفعّل بعد"},403);return json({ok:true,role:"user",user:{username:row.username,email:row.email,password:undefined,balance:Number(row.balance||0),isVerified:true,createdAt:row.created_at}})}
if(action==="register"){if(username.toLowerCase()===(env.ADMIN_USERNAME||"admin").toLowerCase())return json({error:"اسم المستخدم محجوز"},409);if(username.length<3||!/^\\S+@\\S+\\.\\S+$/.test(email)||password.length<4)return json({error:"بيانات الحساب غير صالحة"},400);const exists=await env.DB.prepare("SELECT username,email FROM users WHERE username=?1 OR email=?2 LIMIT 1").bind(username,email).first();if(exists)return json({error:"اسم المستخدم أو البريد مستخدم مسبقاً"},409);const pending=await env.DB.prepare("SELECT username FROM pending_users WHERE username=?1 OR email=?2 LIMIT 1").bind(username,email).first();if(pending)return json({error:"لديك طلب تفعيل سابق، تحقق من بريدك"},409);const code=String(Math.floor(100000+Math.random()*900000));const ph=await makeHash(password);await env.DB.prepare("INSERT INTO pending_users(username,email,password_hash,verification_code,expires_at,created_at) VALUES(?,?,?,?,datetime('now','+15 minutes'),datetime('now'))").bind(username,email,ph,code).run();if(!(await sendEmail(env,email,username,code)))return json({error:"تعذر إرسال البريد. تحقق من إعدادات EmailJS في Cloudflare."},500);return json({ok:true})}
if(action==="verify"){if(!username||!/^[0-9]{6}$/.test(String(b.code||"")))return json({error:"رمز التفعيل غير صحيح"},400);const p=await env.DB.prepare("SELECT * FROM pending_users WHERE username=?1 AND verification_code=?2 AND expires_at>datetime('now') LIMIT 1").bind(username,String(b.code)).first();if(!p)return json({error:"رمز التفعيل غير صحيح أو منتهي"},400);await env.DB.prepare("INSERT INTO users(username,email,password_hash,is_verified,balance,created_at) VALUES(?,?,?,1,0,?)").bind(p.username,p.email,p.password_hash,p.created_at).run();await env.DB.prepare("DELETE FROM pending_users WHERE username=?1").bind(username).run();return json({ok:true,user:{username:p.username,email:p.email,password:undefined,balance:0,isVerified:true,createdAt:p.created_at}})}
if(action==="logout"){return json({ok:true},200,{"Set-Cookie":"idleb_admin=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0"})}return json({error:"Unknown action"},400)}
